spring:
  application:
    name: chanlog

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liGQzB5u0qpEJgOQ
            client-secret: 7a052982e7f58824b1f17a44a0eaa50bc5079a4d
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id


  datasource:
    url: jdbc:mysql://localhost:3306/EXAMDB
    username: chanchangood
    password: chan2581
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012